version: "3"
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /opt/docker-configs/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart:
      always
